### [Tensorflow API](https://www.tensorflow.org/api_docs/python/tf/transpose)

tf.convert_to_tensor()   
tf.Variable()  
tf.random.normal(shape, mean=0.0, stddev=1.0)  高斯分配  
tf.random.truncated_normal(shape, mean=0.0, stddev=1.0)  超過兩倍stddev 重新隨機  
tf.random.uniform(shape, minval=0, maxval=None) 隨機均勻分配  
tf.transpose(a, perm=None)  維度置換  
tf.expand_dims(input, axis)  維度擴張  
tf.stack(values, axis=0)  陣列合併  
tf.unstack(value, num=None, axis=0)  陣列分離  
tf.split(value, num_or_size_splits, axis=0)  陣列切分  
tf.reshape(tensor, shape)  
tf.sort(values, axis=-1, direction='ASCENDING') 值排序direction='DESCENDING'  
tf.argsort(values, axis=-1, direction='ASCENDING')  索引 值排序  
tf.math.top_k(values, k=5)  
tf.pad(tensor, paddings) padding [上,下],[左,右]  
tf.clip_by_value(t, clip_value_min, clip_value_max)  設定上下限值
### 陣列運算
tf.add()  
tf.matmul()  
tf.reduce_mean(input_tensor, axis=None, keepdims=False)  維度平均值  
tf.argmax(input, axis=None, output_type=tf.dtypes.int64)  維度最高值 index  


In [1]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(13)

In [2]:
a = tf.constant([1,2,3])
print(a)
b = np.array([1,2,3])
print(b)
c = tf.convert_to_tensor(b)
print(c)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
[1 2 3]
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [3]:
a = tf.ones(6)
print(a)
b = np.ones(6)
print(b)
c = tf.Variable(a,name='AAA')
print(c)

tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)
[1. 1. 1. 1. 1. 1.]
<tf.Variable 'AAA:0' shape=(6,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>


In [4]:
a = tf.random.normal([6,6],mean=0, stddev=1)
print(a)
b = tf.random.truncated_normal((6,6),mean=0, stddev=0.1)
print(b)
c = tf.random.uniform((6,6),minval=0, maxval=1)
print(c)

tf.Tensor(
[[ 0.46733698  0.89927393 -0.78262424  1.2429025   0.91533005 -0.01959391]
 [-0.91800916  1.3692256  -1.31887     0.21624413 -1.1789111   0.60704744]
 [ 0.6109831   1.8275427   1.0842904   0.5007278  -1.0628445  -0.39373967]
 [-0.6633529  -0.11908418 -0.84424454 -0.8022675  -1.7084516   0.870811  ]
 [ 0.45595148  0.07939936  1.2668875  -1.5246252   0.41710547  0.9672959 ]
 [-0.7834893  -1.5207744   0.6580479  -0.72674286  0.9868633   0.55997133]], shape=(6, 6), dtype=float32)
tf.Tensor(
[[-0.10572089  0.03422752 -0.06972283  0.06160088  0.11293981  0.01581248]
 [ 0.00137381 -0.11582494  0.01400663 -0.12974095  0.18685198 -0.03969903]
 [ 0.0041482   0.10200614 -0.11151971  0.02647186  0.05471441 -0.15147632]
 [ 0.03979918  0.01785305 -0.10575604 -0.12299742  0.03118414  0.09764815]
 [ 0.14534749  0.1480333  -0.029688   -0.04189356 -0.03023089  0.15326816]
 [ 0.04878144 -0.022572    0.03277205  0.07772904 -0.05893312 -0.02636266]], shape=(6, 6), dtype=float32)
tf.Tensor(
[[0.2

In [5]:
a = tf.ones([2,3,4,5])
print(a.shape)
a = tf.transpose(a, perm=[3,2,1,0])
print("tf.transpose")
print(a.shape)

(2, 3, 4, 5)
tf.transpose
(5, 4, 3, 2)


In [6]:
a = tf.random.normal([2,3,4])
print(a.shape)
print("expand_dims axis=0")
a = tf.expand_dims(a, axis=0)
print(a.shape)
print("expand_dims axis=-1")
a = tf.expand_dims(a, axis=-1)
print(a.shape)

(2, 3, 4)
expand_dims axis=0
(1, 2, 3, 4)
expand_dims axis=-1
(1, 2, 3, 4, 1)


In [7]:
a = tf.ones([1,2,3])
b = tf.zeros([1,2,3])
print(a)
print(b)
c = tf.stack((a,b), axis=0)
print(c)
d = tf.stack((a,b), axis=-1)
print(d)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[[1. 1. 1.]
   [1. 1. 1.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]]]], shape=(2, 1, 2, 3), dtype=float32)
tf.Tensor(
[[[[1. 0.]
   [1. 0.]
   [1. 0.]]

  [[1. 0.]
   [1. 0.]
   [1. 0.]]]], shape=(1, 2, 3, 2), dtype=float32)


In [8]:
a = tf.ones([2,32,3])
print("a",a.shape)
a,b,c = tf.unstack(a, axis=2)
print("unstack axis=2")
print("a",a.shape)
print("b",b.shape)
print("c",c.shape)

a (2, 32, 3)
unstack axis=2
a (2, 32)
b (2, 32)
c (2, 32)


In [9]:
a = tf.ones([2,32,3])
print("a",a.shape)
b,c = tf.split(a, axis=1, num_or_size_splits=2)
print("\tsplit")
print("b",b.shape)
print("c",c.shape)

a (2, 32, 3)
	split
b (2, 16, 3)
c (2, 16, 3)


In [10]:
a = [3,4,1,2,6]
b = tf.sort(a)
print(a)
print("\tsort")
print(b)

[3, 4, 1, 2, 6]
	sort
tf.Tensor([1 2 3 4 6], shape=(5,), dtype=int32)


In [11]:
a = [1,2,6,5,4,3]
b = tf.argsort(a)
print(a)
print("\targsort")
print(b)

[1, 2, 6, 5, 4, 3]
	argsort
tf.Tensor([0 1 5 4 3 2], shape=(6,), dtype=int32)


In [12]:
a = [1,2,6,5,4,3]
b = tf.math.top_k(a, k=3)
print(a)
print("\ttf.math.top_k")
print("indices",b.indices)
print("values",b.values)
print("a[2]=6")
print("a[3]=5")
print("a[4]=4")

[1, 2, 6, 5, 4, 3]
	tf.math.top_k
indices tf.Tensor([2 3 4], shape=(3,), dtype=int32)
values tf.Tensor([6 5 4], shape=(3,), dtype=int32)
a[2]=6
a[3]=5
a[4]=4


In [13]:
a = tf.random.normal((3,3))
b = tf.pad(a,[[2,1],[1,2]])
print(a)
print("\t\tpad [上,下],[左,右]")
print("\t\t[[2,1],[1,2]]")
print(b)
print("\t\ta.shape",a.shape)
print("\t\tb.shape",b.shape)

tf.Tensor(
[[ 1.3927455  -0.45965314  0.49407616]
 [ 0.17237073  0.93350935  1.6913122 ]
 [ 0.91713065 -0.16278401  0.39941907]], shape=(3, 3), dtype=float32)
		pad [上,下],[左,右]
		[[2,1],[1,2]]
tf.Tensor(
[[ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.          1.3927455  -0.45965314  0.49407616  0.          0.        ]
 [ 0.          0.17237073  0.93350935  1.6913122   0.          0.        ]
 [ 0.          0.91713065 -0.16278401  0.39941907  0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]], shape=(6, 6), dtype=float32)
		a.shape (3, 3)
		b.shape (6, 6)


In [14]:
a = tf.random.normal([3,3])
print(a)
print("\tclip_ba_value 0~1")
b = tf.clip_by_value(a, 0, 1)
print(b)

tf.Tensor(
[[-1.4116935   0.1200662  -0.72520065]
 [-1.0911381   0.6683593  -0.36648452]
 [-0.01737416  0.88172203 -0.8082091 ]], shape=(3, 3), dtype=float32)
	clip_ba_value 0~1
tf.Tensor(
[[0.         0.1200662  0.        ]
 [0.         0.6683593  0.        ]
 [0.         0.88172203 0.        ]], shape=(3, 3), dtype=float32)


In [67]:
a = [[1,2],[3,4]]
b = [[4,3],[2,1]]
print("a",a,np.array(a).shape)
print("b",b,np.array(b).shape)
print("\ta+b\t 尾數shape同樣才能相加")
print(tf.add(a,b))
a = [[1,2],[3,4],[5,6]]
b = [[1,2]]
print("a",a,np.array(a).shape)
print("b",b,"\t\t  ",np.array(b).shape)
print(tf.add(a,b))

a [[1, 2], [3, 4]] (2, 2)
b [[4, 3], [2, 1]] (2, 2)
	a+b	 尾數shape同樣才能相加
tf.Tensor(
[[5 5]
 [5 5]], shape=(2, 2), dtype=int32)
a [[1, 2], [3, 4], [5, 6]] (3, 2)
b [[1, 2]] 		   (1, 2)
tf.Tensor(
[[2 4]
 [4 6]
 [6 8]], shape=(3, 2), dtype=int32)


In [69]:
a = [[2,3],[4,5],[6,7]]
b = [[5,4],[3,2]]
print("a",a)
print("b",b)
print("\ta*b")
c = tf.matmul(a,b)
print(c)
print()
print("a[0][0]=2 * b[0][0]=5 + a[0][1]=3 * b[1][0]=3\t19")
print("a[0][0]=2 * b[0][1]=4 + a[0][1]=3 * b[1][1]=2\t14")
print()
print("a[1][0]=4 * b[0][0]=5 + a[1][1]=5 * b[1][0]=3\t35")
print("a[1][0]=4 * b[0][1]=4 + a[1][1]=5 * b[1][1]=2\t26")
print()
print("a[2][0]=6 * b[0][0]=5 + a[2][1]=7 * b[1][0]=3\t51")
print("a[2][0]=6 * b[0][1]=4 + a[2][1]=7 * b[1][1]=2\t38")
print("a.shape",np.array(a).shape)
print("b.shape",np.array(b).shape)
print("c.shape",np.array(c).shape,"a*b 取a的頭,b的尾")
print("a(6,32,4) * b(4,6,8) = c(6,32,8)")
print("a的頭 6,32\tb的尾 8 => 6,32,8")

a [[2, 3], [4, 5], [6, 7]]
b [[5, 4], [3, 2]]
	a*b
tf.Tensor(
[[19 14]
 [35 26]
 [51 38]], shape=(3, 2), dtype=int32)

a[0][0]=2 * b[0][0]=5 + a[0][1]=3 * b[1][0]=3	19
a[0][0]=2 * b[0][1]=4 + a[0][1]=3 * b[1][1]=2	14

a[1][0]=4 * b[0][0]=5 + a[1][1]=5 * b[1][0]=3	35
a[1][0]=4 * b[0][1]=4 + a[1][1]=5 * b[1][1]=2	26

a[2][0]=6 * b[0][0]=5 + a[2][1]=7 * b[1][0]=3	51
a[2][0]=6 * b[0][1]=4 + a[2][1]=7 * b[1][1]=2	38
a.shape (3, 2)
b.shape (2, 2)
c.shape (3, 2) a*b 取a的頭,b的尾
a(6,32,4) * b(4,6,8) = c(6,32,8)
a的頭 6,32	b的尾 8 => 6,32,8


In [102]:
a = [[1.,2.,3.],[4.,5.,6.]]
print(a)
b = tf.reduce_mean(a, axis=0)
print("a.shape",np.array(a).shape)
print("reduce_mean axis=0",b.numpy())
print("消滅0軸，a.shape(3,)")
print("a[0][0]=1.0 + a[1][0]=4.0 / a[0].shape=2  => 2.5")
print()
c = tf.reduce_mean(a, axis=1)
print("reduce_mean axis=1",c.numpy())
print("消滅1軸，a.shape(2,)")
print("a[0][0]=1.0 + a[0][1]=2.0 + a[0][2]=3.0 / a[1].shape=3 => 2.0")

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
a.shape (2, 3)
reduce_mean axis=0 [2.5 3.5 4.5]
消滅0軸，a.shape(3,)
a[0][0]=1.0 + a[1][0]=4.0 / a[0].shape=2  => 2.5

reduce_mean axis=1 [2. 5.]
消滅1軸，a.shape(2,)
a[0][0]=1.0 + a[0][1]=2.0 + a[0][2]=3.0 / a[1].shape=3 => 2.0


In [129]:
a = [[1,2,3,4],[4,3,2,1],[8,1,2,5]]
print(a)
print("a.shape",np.array(a).shape)
a = tf.convert_to_tensor(a)
b = tf.argmax(a, axis=0)
print("tf.argmax axis=0",b.numpy())
print("a[0][0]=1 a[1][0]=4 a[2][0]=8 index=2")
print("a[0][1]=2 a[1][1]=3 a[2][1]=1 index=1")
print()
c = tf.argmax(a, axis=1)
print("tf.argmax axis=1",c.numpy())

[[1, 2, 3, 4], [4, 3, 2, 1], [8, 1, 2, 5]]
a.shape (3, 4)
tf.argmax axis=0 [2 1 0 2]
a[0][0]=1 a[1][0]=4 a[2][0]=8 index=2
a[0][1]=2 a[1][1]=3 a[2][1]=1 index=1

tf.argmax axis=1 [3 0 0]
